name: Update Material Icons

on:
  schedule:
    # Runs every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # allows manual trigger

jobs:
  update-icons:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Update icons
        run: node scripts/update-icons.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/icons.json
          git commit -m "Update Material Icons JSON" || echo "No changes to commit"
          git push

